version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=spiri12345
      - MYSQL_DATABASE=account
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - 6868:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/account?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "spiri12345",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.defer-datasource-initialization" : "true",
        "spring.sql.init.mode" : "always",
        "jwt.secretKey" : "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970",
        "jwt.expiration" : "180000",
        "springdoc.api-docs.path" : "/api-docs"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: