package com.customer.account.request;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * The login form used to login
 */
public class LoginRequest {
    /**
     * Username used to login
     */
    @NotBlank(message = "Username is mandatory")
    @Size(min = 3, max = 20, message = "Username must be between 3 and 20 characters")
    private String username;

    /**
     * Password that was autogenerated during registration
     */
    @NotBlank(message = "password is mandatory")
    @Size(max = 20, message = "Password must be 10 characters")
    private String password;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}
